### ISSUE TITLE
websockets breakdown

### ISSUE THREAD

**Issue by kaktus42** [calitek/ReactPatterns#3]
```
$ npm run start

> ReactPatterns.15-ReFluxWebSocket@1.0.0 start /tmp/ReactPatterns/React.15/ReFluxWebSocket
> node js/server.js

module.js:327
    throw err;
    ^

Error: Cannot find module './socket/getsetdata'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/tmp/ReactPatterns/React.15/ReFluxWebSocket/js/mainsocket.js:3:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```

**Comment by calitek** [comment]
You will need to start in the project root. The modules are referenced relative to the expected start location.

**Comment by kaktus42** [comment]
it is a misspelling of a module.
It's fixed in the pull request.

**Comment by calitek** [comment]
Your correct. Sorry I missed that. The change is made.

**Comment by kaktus42** [comment]
you don't like pull request, eh?
